# Generated by Django 5.0.6 on 2025-09-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('type', models.CharField(choices=[('WEBSITE', 'Website'), ('TELEGRAM_CHANNEL', 'Telegram Channel')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('JOB', 'Job'), ('PROJECT', 'Project'), ('COMPETITION', 'Competition')], db_index=True, max_length=20)),
                ('parser', models.CharField(blank=True, help_text='websites.py function name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(max_length=1000)),
                ('category', models.CharField(choices=[('JOB', 'Job'), ('PROJECT', 'Project'), ('COMPETITION', 'Competition')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('posted_to_channel', models.BooleanField(db_index=True, default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.source')),
            ],
            options={
                'indexes': [models.Index(fields=['posted_to_channel', 'created_at'], name='core_post_posted__88b309_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('source', 'link'), name='uniq_source_link'),
        ),
    ]
